CREATE TABLE LABORATORY_EXAM(
       LBEX_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
       LBEX_LBRT_ID INTEGER NOT NULL,
       LBEX_EXAM_ID INTEGER NOT NULL,
       
                    CONSTRAINT FK_LBEX_LBRT_ID
                    FOREIGN KEY (LBEX_LBRT_ID) 
                    REFERENCES LABORATORY (LBRT_ID)ON DELETE CASCADE ON UPDATE RESTRICT,
                     
                    CONSTRAINT FK_LBEX_EXAM_ID
                    FOREIGN KEY (LBEX_EXAM_ID)
                    REFERENCES EXAM (EXAM_ID)ON DELETE CASCADE ON UPDATE RESTRICT
)